### ISSUE TITLE
Implement bin management

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/safestore#1]
**Tasks To Do**
- [ ] When user logs in, display a list of bins stored in their google drive.
- [ ] User can select a bin to open. prompts for password.
- [ ] User can delete a bin. confirm password before delete.
- [ ] An add new button will be visible
- [ ] When adding a new bin, take password and confirm password. also, check if same bin already exists.
- [ ] User can clone a bin. first take old password, then new password and confirm password. check if same bin already exists.
- [ ] User can move a bin. clone first, then delete old.

**Additional**
- [ ] Use qr image of bin id as logo
- [ ] Bin description could be use for additional meta information
- [ ] Show grid view of qr images for bins. sort them by modify time.

**Required API**
- [ ] Service to update description of a drive file
